### PR TITLE
 dz5

### PR DESCRIPTION
**Pull request by VasilevichDev**

### CODE REVIEW

**Comment by VasilevichDev** [comment]
photo_2021-05-02_22-39-04 (3)
photo_2021-05-02_22-39-04 (4)
photo_2021-05-02_22-39-04
photo_2021-05-02_22-39-04 (2)

**Review by Gizcerbes — COMMENTED** [review]
Not exist activity_main
   `<Button
        android:id="@+id/button5"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="32dp"
        android:text="@string/homework_5"
        app:layout_constraintEnd_toEndOf="@+id/button3"
        app:layout_constraintHorizontal_bias="1.0"
        app:layout_constraintStart_toStartOf="@+id/button3"
        app:layout_constraintTop_toBottomOf="@+id/button3" />`

**Review by Gizcerbes — COMMENTED** [review]
Not exist 
`findViewById<Button>(R.id.button5).setOnClickListener { onClickGoToMaterial(it) }`

**Review by VasilevichDev — COMMENTED** [review]
made button for homework 5, it must working now

**Review by 10011001zxxz — APPROVED** [review]

**Review by OcheretnyArtem — APPROVED** [review]

**Review by Berikz80 — APPROVED** [review]

**Review by artemVash — APPROVED** [review]

**Review by TMSlebedev — APPROVED** [review]

**Pull request merged**
